
token_list = {
    "tk_suma" : "+",
    "tk_mult" : "*",
    "tk_remainder" : "%",
    "tk_par_izq" : "(",
    "tk_par_der" : ")",
    "tk_cor_izq" : "[",
    "tk_cor_der" :  "]",
    "tk_coma" : ",",
    "tk_dos_puntos" : ":",
    "tk_punto" : ".",
    "tk_menor_igual" : "<=",
    "tk_menor" : "<",
    "tk_mayor_igual" : ">=",
    "tk_mayor" : ">",
    "tk_comparacion" : "==",
    "tk_asig" : "=",
    "tk_ejecuta" : "->",
    "tk_menos" : "-",
    "tk_distinto" :  "!=",
    "tk_division" :  "//",
    "tk_ident" :  "IDENT",
	"tk_newline" : "NEWLINE",
    "tk_dedent" : "DEDENT",
    "tk_cadena" : "STRING",
    "tk_entero" : "INTEGER",
    "id" : "ID",
    "def" : "DEF",	
    "tk_asig" : "ASIG",
    "$" : "EOF",
    "len": "len",
    "bool": "bool",
    "none": "none",
    "return": "return",
    "False" : "False",
    "if": "if",
    "int":"int",
    "pass":"pass",
    "for" : "for",
    "while":"while",
    "not":"not",
    "True": "True",
    "print":"print",
    "is":"is",
    "and":"and",
    "else":"else",
    "or":"or"


}
